-- ─── ESQUEMA DE BASE DE DATOS PARA SUPABASE ───────────────────────────────────────

-- 1. Tabla de resultados de wallets encontradas
CREATE TABLE IF NOT EXISTS wallet_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT NOT NULL,
    eth_address TEXT,
    eth_balance NUMERIC(30, 10) DEFAULT 0,
    bsc_address TEXT,
    bsc_balance NUMERIC(30, 10) DEFAULT 0,
    btc_address TEXT,
    btc_balance NUMERIC(30, 10) DEFAULT 0,
    sol_address TEXT,
    sol_balance NUMERIC(30, 10) DEFAULT 0,
    found_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de progreso y estadísticas del escáner
CREATE TABLE IF NOT EXISTS scan_stats (
    id TEXT PRIMARY KEY DEFAULT 'main',
    total_phrases BIGINT DEFAULT 0,
    processed BIGINT DEFAULT 0,
    found_wallets INT DEFAULT 0,
    is_running BOOLEAN DEFAULT true,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla para almacenar frases mnemónicas en la base de datos
CREATE TABLE IF NOT EXISTS mnemonic_seeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phrase TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Permisos RLS
ALTER TABLE wallet_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE scan_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE mnemonic_seeds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir todo resultados" ON wallet_results FOR ALL USING (true);
CREATE POLICY "Permitir todo stats" ON scan_stats FOR ALL USING (true);
CREATE POLICY "Permitir todo seeds" ON mnemonic_seeds FOR ALL USING (true);
