-- ─── ESQUEMA DE BASE DE DATOS MULTIUSUARIO Y ADMIN ────────────────────────────

-- 1. Tabla de resultados de wallets (con soporte multiusuario)
CREATE TABLE IF NOT EXISTS wallet_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL DEFAULT 'public',
    user_email TEXT,
    phrase TEXT NOT NULL,
    eth_address TEXT,
    eth_balance NUMERIC(30, 10) DEFAULT 0,
    bsc_address TEXT,
    bsc_balance NUMERIC(30, 10) DEFAULT 0,
    btc_address TEXT,
    btc_balance NUMERIC(30, 10) DEFAULT 0,
    sol_address TEXT,
    sol_balance NUMERIC(30, 10) DEFAULT 0,
    found_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabla de progreso y estadísticas del escáner por usuario
CREATE TABLE IF NOT EXISTS scan_stats (
    id TEXT PRIMARY KEY DEFAULT 'main',
    user_id TEXT DEFAULT 'public',
    total_phrases BIGINT DEFAULT 0,
    processed BIGINT DEFAULT 0,
    found_wallets INT DEFAULT 0,
    is_running BOOLEAN DEFAULT true,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabla para almacenar frases mnemónicas personales por usuario
CREATE TABLE IF NOT EXISTS mnemonic_seeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL DEFAULT 'public',
    phrase TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabla de perfiles de usuario y roles (Admin / User)
CREATE TABLE IF NOT EXISTS user_profiles (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'user', -- 'admin' o 'user'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Deshabilitar RLS estricto para gestionar acceso seguro via Backend SupabaseAdmin
ALTER TABLE wallet_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE scan_stats DISABLE ROW LEVEL SECURITY;
ALTER TABLE mnemonic_seeds DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;
